"""CLI command: spectral android cert."""

from __future__ import annotations

from pathlib import Path

import click

from cli.helpers.console import console


@click.command()
@click.argument(
    "cert_path",
    default=None,
    required=False,
    type=click.Path(exists=True),
)
def cert(cert_path: str | None) -> None:
    """Push a CA certificate to the Android device.

    Defaults to ~/.mitmproxy/mitmproxy-ca-cert.pem (generated by mitmproxy
    on first run). The cert is pushed to /sdcard/ as a .crt file.
    """
    from cli.commands.android.external_tools.adb import check_adb, push_cert

    check_adb()

    if cert_path:
        path = Path(cert_path)
    else:
        path = Path.home() / ".mitmproxy" / "mitmproxy-ca-cert.pem"
        if not path.exists():
            console.print(
                f"[red]No mitmproxy cert found at {path}.[/red]\n"
                "  Run 'mitmproxy' once to generate it, then retry."
            )
            raise SystemExit(1)

    console.print(f"[bold]Pushing certificate:[/bold] {path}")
    device_filename = push_cert(path)

    console.print(f"[green]Certificate pushed to /sdcard/{device_filename}[/green]")
    console.print()
    console.print("[bold]Install on device:[/bold]")
    console.print("  Settings > Security > Install from storage > CA certificate")
    console.print(f"  Select {device_filename}")
